export enum EActionTypes {
  SEARCH_MOVIES_PENDING = 'SEARCH_MOVIES_PENDING',
  SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS',
  SEARCH_MOVIES_ERROR = 'SEARCH_MOVIES_ERROR',
  SEARCH_MOVIE_PENDING = 'SEARCH_MOVIE_PENDING',
  SEARCH_MOVIE_SUCCESS = 'SEARCH_MOVIE_SUCCESS',
  SEARCH_MOVIE_ERROR = 'SEARCH_MOVIE_ERROR',
  DELETE_MOVIE = 'DELETE_MOVIE',
  DEFAULT = 'DEFAULT',
}
